### ISSUE TITLE
VNC

### ISSUE THREAD

**Issue by MPParsley** [hanzelpeter/dispmanx_vnc#12]
It would seem that this fork is more elaborated: https://github.com/patrikolausson/dispmanx_vnc

What is the advantage of dispmanx_vnc over the official (Real)vnc documentation? https://www.raspberrypi.org/documentation/remote-access/vnc/README.md

**Comment by hanzelpeter** [comment]
Hello. It allowed to show content that normal vnc could not handle. Like minecraftpi and all dispamanx demos. But I think now realvnc is capable of handling this. So you can use normal realvnc.

**Comment by MPParsley** [comment]
Thanks for the quick reply!
