### ISSUE TITLE
license

### ISSUE THREAD

**Issue by graysky2** [hanzelpeter/dispmanx_vnc#14]
What license are you using for this software?

**Comment by hanzelpeter** [comment]
Hello. I have set no licence. You can use it for ever what you want.

**Comment by graysky2** [comment]
I packaged it for Arch ARM.  Would you include declare a license type to keep things compliant?  MIT is a good one: https://github.com/graysky2/profile-sync-daemon/blob/master/MIT

**Comment by graysky2** [comment]
Send you a PR.

**Comment by hanzelpeter** [comment]
Merged
