### ISSUE TITLE
failed to start error undefined symbol: _ZNK9libconfig6Config11lookupValueEPKcRSs

### ISSUE THREAD

**Issue by riker65** [hanzelpeter/dispmanx_vnc#20]
Hi

the vnc server worked like a charm

all of a sudden I have:

dispmanx_vncserver[872]: /usr/bin/dispmanx_vncserver: symbol lookup error: /usr/bin/dispmanx_vncserver: undefined symbol: _ZNK9libconfig6Config11lookupValueEPKcRSs

any idea?

thanks T

**Comment by hanzelpeter** [comment]
What distribution do you have? Did you update to latest version? 
Have you tried to recomplete it after update of packaged?

**Comment by riker65** [comment]
Hi 
thanks 
ok will try to recompile .
I am using osmc and recompiled it just a month ago.
it was working and all of a suddon I could not connect.
will update after I am done.

**Comment by riker65** [comment]
solved now after rebuild
thanks
