### ISSUE TITLE
libraries renamed in Stretch

### ISSUE THREAD

**Issue by zeogeo** [hanzelpeter/dispmanx_vnc#24]
In Stretch, libraries were renamed to libbrcmEGL.so and libbrcmGLESv2.so. 
Makefiles need to be modified to link the 2 libraries with different names: -lbrcmEGL -lbrcmGLESv2

**Comment by hanzelpeter** [comment]
makefile and makeit changed.

**Comment by zeogeo** [comment]
thank you
