### ISSUE TITLE
no keyboard and mouse under X

### ISSUE THREAD

**Issue by chengjianwen** [hanzelpeter/dispmanx_vnc#27]
I installed dispmanx_vncserver on latest Raspbian, Raspbian lite and Raspbian full. It seems there without keyboard and mouse under X.

The modules uinput and evdev are loaded. I searched everywhere and can't find any useful information about it.

Thanks

**Comment by hanzelpeter** [comment]
This has probably to do with new libinput used in Xorg. I can't still find a way how to make it work with libinput. Now I changed xorg conf to use old evdev system and this way mouse and keyboard works. I used Google how to set xorg to use evdev.

**Comment by chengjianwen** [comment]
I remove xserver-xorg-input-libinput and install xserver-xorg-input-evdev, it works now.
