### ISSUE TITLE
 libvncserver-dev : Depends: libgnutls28-dev but it is not going to be installed

### ISSUE THREAD

**Issue by ctugt** [hanzelpeter/dispmanx_vnc#6]
sudo apt-get install libvncserver-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvncserver-dev : Depends: libgnutls28-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by hanzelpeter** [comment]
Hello, This is on rasbian? Did you do ``sudo apt-get update`` ?

**Comment by ctugt** [comment]
nope its on oscm, and yes i did apt-get update. i seems its using a newe libgnutils28

**Comment by hanzelpeter** [comment]
Sorry this is about package management and I don't know what can be the cause.

**Comment by ctugt** [comment]
np thx for responding
